services:
  web:
    build: .
    ports:
      - "127.0.0.1:8765:8765"
    environment:
      VOICEVOX_BASE_URL: "http://voicevox:50021"
    volumes:
      - .:/app
    depends_on:
      - voicevox

  voicevox:
    image: voicevox/voicevox_engine:cpu-latest
    ports:
      - "127.0.0.1:50021:50021"
    logging:
      driver: "none"
